version: "2"
output:
  sort-order:
    - file
    - severity
    - linter
linters:
  enable:
    - wsl_v5
  disable:
    - exhaustruct
    - ireturn
    - testpackage
    - varnamelen
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/google
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr
    exhaustruct:
      exclude:
        - .*_test.go
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tree_dump
      - third_party
      - builtin
      - examples
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tree_dump*
      - third_party$
      - builtin$
      - examples$
