language: go
sudo: false

go:
- "1.9"
- "1.10"
- "1.11"
- "tip"

# matrix:
#   allow_failures:
#     - go: 1.1.2

install:
  - make bootstrap

before_script:
  - go vet ./...

script:
  - make
  - make test-cover-builder
  - $HOME/gopath/bin/goveralls -coverprofile=/tmp/art_coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
