name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go: ['stable', 'oldstable']
        os: ['ubuntu-latest']
        
    runs-on: ${{ matrix.os }}
    
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      name: Install Go
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
        cache: true

    # - name: Go Environment
    #   run: |
    #     go version
    #     go env

    - name: "Run QA: mod, fmt, vet, lint, staticcheck, vulncheck, goses..."
      run: ./make qa

    - name: "Run Tests..."
      run: ./make qa/test
